runtime: python
env: flex
entrypoint: gunicorn -b :$PORT wishlist.wsgi

runtime_config:
  python_version: 3

env_variables:
  WISHLIST_DB_PW: 1234abcd

beta_settings:
  cloud_sql_instances: wishlist-199319:us-central1:postgressql